baseURL = 'http://dusableproject.xyz/'
languageCode = 'en-us'
title = 'CCC DuSable Project'
theme = "ananke"
resourceDir = "../resources"
# Makes Pages Not Plural
pluralizeListTitles = 'false'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[params]
  featured_image = '/Img/DuSable.png'
  author = "CCC"