baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'CCC DuSable'
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  featured_image = '/Img/DuSable.png'
  author = "CCC"